### ISSUE TITLE
GameUserSettings not accepted on Synology

### ISSUE THREAD

**Issue by derFlask** [phantium/docker-ark#1]
Hi, I'm running the docker on a Synology NAS. Everything works well, exept that the GameUserSettings.ini will not be loaded. Instead of my defined settings, the Server takes some ramdom settings. Any ideas where the error might be?

Thanks!

**Comment by phantium** [comment]
Hi, thanks for reporting this. I will look into it.

**Comment by phantium** [comment]
I really need more information on what you're doing to run the image on Synology.
Synology is very limited in terms of supported features for Docker.

In my case I don't even get further than:
``Grabbing SteamCMD...

tar: steamcmd_linux.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Updating ARK...
```
/usr/local/bin/ark: line 32: ./steamcmd.sh: No such file or directory
/usr/local/bin/ark: line 36: cd: /data/ark/arkdedicated/ShooterGame/Binaries/Linux/: No such file or 

Launching ARK Dedicated Server...
/usr/local/bin/ark: line 41: ./ShooterGameServer: No such file or directory
```

**Comment by phantium** [comment]
Hmpf, giving everyone permissions on the mounted folder seems to resolve that issue.
Quite a nasty solution though.

**Comment by derFlask** [comment]
Honestly I just followed your instructions ;-)
Strangely everything worked just fine. What DSM Version do you have? I've
got  a 1515+ with version  5.2-5644 V2

phantium <notifications@github.com> schrieb am Fr., 22. Jan. 2016 14:53:

**Comment by phantium** [comment]
My instructions are not for docker on synology, it is untested. Docker
works well but synology works a bit differently.

I believe my version is 5.3 or so as I updated today.

**Comment by derFlask** [comment]
I thought so but I also thought 'give it a try' ;-)

Oh, I forgot that I made it as  root via PUTTY!

phantium <notifications@github.com> schrieb am Fr., 22. Jan. 2016 18:23:

**Comment by Blindsyde** [comment]
Hi guys, I was just poking around to see if I could host Ark on my synology and ended up here, is this possible with the instructions on the home page and does it save correctly now?

**Comment by phantium** [comment]
This project has been abandoned, I will not be doing any further updates.
